export const colors = {
  background: '#000000',
  surface: '#0E0E10',
  surfaceBorder: '#1F1F22',
  textPrimary: '#FFFFFF',
  textSecondary: '#8E8E93',
  textOnLight: '#000000',
  textOnLightSecondary: '#6B6B70',
  border: '#3A3A3A',
  borderFocused: '#FFFFFF',
  buttonPrimaryFrom: '#FFFFFF',
  buttonPrimaryTo: '#CFCFCF',
  buttonPrimaryText: '#000000',
  cardGradientFrom: '#1A1B1E',
  cardGradientTo: '#0C0C0E',
  cardBorder: '#26272B',
  cardLightGradientFrom: '#FFFFFF',
  cardLightGradientTo: '#DEDEE3',
  accent: '#C5F23D',
  danger: '#FF3B30',
};
